default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: inside-dev
  user: postgres
  password: paswd

test:
  <<: *default
  database: inside-test
  user: postgres
  password: paswd
